import QtQuick
import QtQuick.Controls
import QtQuick.Layouts
import QtQuick.Dialogs

ApplicationWindow {
 id:root; visible:true; width:1500; height:920; minimumWidth:1100; minimumHeight:700
 title:"Store Data Assistant 6.2"; color:"#07111f"
 property color fg:"#f8fafc"; property color muted:"#94a3b8"; property color panel:"#0e1b2d"; property color panel2:"#132238"; property color border:"#263850"
 property color blue:"#3b82f6"; property color green:"#22c55e"; property color amber:"#f59e0b"; property color red:"#ef4444"
 property int page:0; property string masterPath:""; property string mappingPath:""; property string repairPath:""; property string analysisPath:""
 property int selectedRow:-1; property bool differencesOnly:true; property var columns:[]; property var resultColumns:[]
 property int total:0; property int correct:0; property int review:0; property int errors:0; property var health:({})
 ListModel{id:mapRows} ListModel{id:valRows} ListModel{id:compareRows} ListModel{id:fixRows} ListModel{id:healthRows} ListModel{id:statRows} ListModel{id:resultRows}
 function name(p){var x=String(p||"").replace(/\\/g,"/").split("/");return x.length?x[x.length-1]:""}
 function scol(s){return s==="ERROR"||s==="UNRESOLVED"?root.red:s==="REVIEW"||s==="REPAIRED"||s==="DIFFERENT"?root.amber:root.green}
 function bg(s){return s==="ERROR"||s==="UNRESOLVED"?"#421820":s==="REVIEW"||s==="REPAIRED"?"#433614":"#113426"}

 FileDialog{id:masterDlg;title:"Choose Master";nameFilters:["Data (*.csv *.xlsx *.xls *.xlsm *.txt *.tsv *.json *.xml)"];onAccepted:{root.masterPath=selectedFile.toString();backend.loadMaster(root.masterPath)}}
 FileDialog{id:uploadDlg;title:"Choose Uploaded File";nameFilters:["Data (*.csv *.xlsx *.xls *.xlsm *.txt *.tsv *.json *.xml)"];onAccepted:{root.mappingPath=selectedFile.toString();backend.loadMapping(root.mappingPath)}}
 FileDialog{id:repairDlg;title:"Choose CSV / Text";nameFilters:["CSV / Text (*.csv *.txt *.tsv)"];onAccepted:{root.repairPath=selectedFile.toString();backend.inspectCSV(root.repairPath)}}
 FileDialog{id:dataDlg;title:"Choose Dataset";nameFilters:["Data (*.csv *.xlsx *.xls *.xlsm *.txt *.tsv *.json *.xml)"];onAccepted:{root.analysisPath=selectedFile.toString();backend.loadFile(root.analysisPath)}}
 FileDialog{id:repairSave;title:"Save Repaired Copy";fileMode:FileDialog.SaveFile;nameFilters:["CSV (*.csv)"];onAccepted:backend.repairCSV(root.repairPath,selectedFile.toString())}
 FileDialog{id:reportSave;title:"Export Comparison";fileMode:FileDialog.SaveFile;nameFilters:["Excel (*.xlsx)","CSV (*.csv)"];onAccepted:backend.exportValidationReport(selectedFile.toString())}
 FileDialog{id:dataSave;title:"Export Result";fileMode:FileDialog.SaveFile;nameFilters:["Excel (*.xlsx)","CSV (*.csv)","JSON (*.json)"];onAccepted:backend.exportCurrentData(selectedFile.toString())}
 MessageDialog{id:errorDlg;title:"Store Data Assistant"}

 Connections{
  target:backend
  function onErrorRaised(m){errorDlg.text=m;errorDlg.open()}
  function onColumnMappingReady(p){var d=JSON.parse(p),fs=["Store Name","SID","Banner","Nielsen Store Code","Trip Received","Last Trip","Address 1","Address 2","Address 3","ZIP","Active / Inactive","Is Census","Is Exceptions","Updated By"];mapRows.clear();for(var i=0;i<fs.length;i++){var f=fs[i],a=d.master[f]||{},b=d.mapping[f]||{},c=Math.min(Number(a.confidence||0),Number(b.confidence||0));mapRows.append({f:f,m:String(a.column||""),u:String(b.column||""),c:c})}}
  function onValidationReady(p){var d=JSON.parse(p);root.total=d.total;root.correct=d.correct;root.review=d.review;root.errors=d.errors;valRows.clear();compareRows.clear();root.selectedRow=-1;for(var i=0;i<d.results.length;i++){var r=d.results[i];valRows.append({row:String(r.row),sid:String(r.sid),store:String(r.storeName),status:String(r.status),problem:String(r.problem)})}}
  function onComparisonDetailReady(p){var d=JSON.parse(p);compareRows.clear();for(var i=0;i<d.rows.length;i++){var r=d.rows[i];compareRows.append({f:String(r.field),m:String(r.master),u:String(r.uploaded),res:String(r.result),sev:String(r.severity)})}}
  function onCsvInspectionReady(p){var d=JSON.parse(p);fixRows.clear();for(var i=0;i<d.problems.length;i++){var r=d.problems[i];fixRows.append({line:String(r.line),exp:String(r.expectedColumns),act:String(r.actualColumns),status:String(r.status),repair:String(r.repair),content:String(r.content)})}}
  function onAnalysisReady(p){var d=JSON.parse(p);root.health=d;root.columns=d.columnNames||[];healthRows.clear();for(var i=0;i<d.columnStats.length;i++){var r=d.columnStats[i];healthRows.append({col:String(r.column),non:String(r.nonBlank),blank:String(r.blank),uniq:String(r.unique),dup:String(r.duplicateValues),num:String(r.numericCount)})}statCol.model=root.columns;statGroup.model=["(No grouping)"].concat(root.columns);searchCol.model=["All columns"].concat(root.columns)}
  function onStatisticsReady(p){var d=JSON.parse(p);statRows.clear();for(var i=0;i<d.rows.length;i++)statRows.append({g:String(d.rows[i].group),v:String(d.rows[i].value)})}
  function onSqlResultReady(p){var d=JSON.parse(p);root.resultColumns=d.columns||[];resultRows.clear();for(var i=0;i<d.rows.length;i++)resultRows.append({vals:d.rows[i]});resultInfo.text=d.totalRows+" row(s); showing "+d.shownRows}
 }

 component Panel:Rectangle{radius:10;color:root.panel;border.width:1;border.color:root.border}
 component Title:Text{color:root.fg;font.pixelSize:24;font.bold:true}
 component Desc:Text{color:root.muted;font.pixelSize:12;wrapMode:Text.WordWrap}
 component Btn:Button{implicitHeight:38;palette.button:root.panel2;palette.buttonText:root.fg}
 component PBtn:Button{implicitHeight:38;palette.button:root.blue;palette.buttonText:"white";font.bold:true}
 component H:Rectangle{property string t:"";implicitHeight:34;color:root.panel2;Text{anchors.fill:parent;anchors.margins:7;text:parent.t;color:root.muted;font.pixelSize:10;font.bold:true;verticalAlignment:Text.AlignVCenter;elide:Text.ElideRight}}
 component Metric:Panel{property string n:"0";property string l:"";property color nc:root.blue;implicitHeight:76;Column{anchors.fill:parent;anchors.margins:11;Text{text:parent.parent.n;color:parent.parent.nc;font.pixelSize:22;font.bold:true}Text{text:parent.parent.l;color:root.muted;font.pixelSize:10;font.bold:true}}}

 header:Rectangle{height:58;color:"#081321";border.width:1;border.color:root.border;RowLayout{anchors.fill:parent;anchors.margins:12;Rectangle{width:34;height:34;radius:8;color:root.blue;Text{anchors.centerIn:parent;text:"DA";color:"white";font.bold:true}}Column{Text{text:"Store Data Assistant";color:root.fg;font.pixelSize:15;font.bold:true}Text{text:"Validation, repair, statistics and local analysis";color:root.muted;font.pixelSize:9}}Item{Layout.fillWidth:true}Text{text:"●  LOCAL ONLY";color:"#86efac";font.bold:true}}}
 footer:Rectangle{height:30;color:"#081321";border.width:1;border.color:root.border;RowLayout{anchors.fill:parent;anchors.leftMargin:12;anchors.rightMargin:12;Text{text:backend.message;color:root.muted;font.pixelSize:10;Layout.fillWidth:true;elide:Text.ElideRight}Text{text:"Store Data Assistant 6.2";color:root.muted;font.pixelSize:9}}}

 RowLayout{
  anchors.fill:parent;spacing:0
  Rectangle{
   Layout.preferredWidth:215;Layout.fillHeight:true;color:"#0b1728";border.width:1;border.color:root.border
   ColumnLayout{anchors.fill:parent;anchors.margins:10;spacing:5
    Text{text:"WORKSPACE";color:root.muted;font.pixelSize:9;font.bold:true;Layout.leftMargin:8;Layout.topMargin:7}
    Repeater{model:["Home","Compare & Validate","Repair CSV / Text","Data Health & Statistics","Explore & Analyze"];delegate:Button{required property string modelData;required property int index;Layout.fillWidth:true;implicitHeight:42;text:modelData;palette.button:root.page===index?"#1d4777":"#0b1728";palette.buttonText:root.fg;onClicked:root.page=index}}
    Item{Layout.fillHeight:true}
    Panel{Layout.fillWidth:true;implicitHeight:75;Column{anchors.fill:parent;anchors.margins:10;Text{text:"Privacy";color:root.fg;font.bold:true;font.pixelSize:10}Text{width:parent.width;text:"Local processing. Source files are not changed automatically.";color:root.muted;font.pixelSize:9;wrapMode:Text.WordWrap}}}
   }
  }

  StackLayout{
   currentIndex:root.page;Layout.fillWidth:true;Layout.fillHeight:true

   Item{ScrollView{anchors.fill:parent;contentWidth:availableWidth;ColumnLayout{width:parent.width;spacing:15;Item{implicitHeight:15}Title{text:"Data Workspace";Layout.leftMargin:25}Desc{text:"Compare stores, repair malformed CSV records, build statistics and explore structured data locally.";Layout.fillWidth:true;Layout.leftMargin:25;Layout.rightMargin:25}GridLayout{Layout.fillWidth:true;Layout.leftMargin:25;Layout.rightMargin:25;columns:2;columnSpacing:12;rowSpacing:12;Repeater{model:[["Compare & Validate","Master vs Uploaded field-by-field comparison.",1],["Repair CSV / Text","Auditable broken-line reconstruction and repaired copy.",2],["Data Health & Statistics","Quality profile plus Count, Sum, Average, Min, Max and grouping.",3],["Explore & Analyze","Search and read-only SQL with tabular results.",4]];delegate:Panel{required property var modelData;Layout.fillWidth:true;implicitHeight:140;ColumnLayout{anchors.fill:parent;anchors.margins:15;Text{text:modelData[0];color:root.fg;font.pixelSize:16;font.bold:true}Desc{text:modelData[1];Layout.fillWidth:true}Item{Layout.fillHeight:true}PBtn{text:"Open";onClicked:root.page=modelData[2]}}}}}}}}

   Item{ScrollView{anchors.fill:parent;contentWidth:availableWidth;ColumnLayout{width:parent.width;spacing:11;Item{implicitHeight:8}Title{text:"Compare & Validate";Layout.leftMargin:22}Desc{text:"Select a result to see the exact Master and Uploaded value for every field.";Layout.fillWidth:true;Layout.leftMargin:22;Layout.rightMargin:22}
    Panel{Layout.fillWidth:true;Layout.leftMargin:22;Layout.rightMargin:22;implicitHeight:145;ColumnLayout{anchors.fill:parent;anchors.margins:12;RowLayout{Layout.fillWidth:true;TextField{Layout.fillWidth:true;readOnly:true;placeholderText:"Master file";text:root.name(root.masterPath)}Btn{text:"Browse";onClicked:masterDlg.open()}}RowLayout{Layout.fillWidth:true;TextField{Layout.fillWidth:true;readOnly:true;placeholderText:"Uploaded / country file";text:root.name(root.mappingPath)}Btn{text:"Browse";onClicked:uploadDlg.open()}}RowLayout{Btn{text:"Detect Columns";enabled:root.masterPath!==""&&root.mappingPath!=="";onClicked:backend.detectStoreColumns()}PBtn{text:"Validate Stores";Layout.fillWidth:true;enabled:root.masterPath!==""&&root.mappingPath!=="";onClicked:backend.validateStores()}}}}
    Panel{Layout.fillWidth:true;Layout.leftMargin:22;Layout.rightMargin:22;implicitHeight:245;ColumnLayout{anchors.fill:parent;anchors.margins:10;Text{text:"Smart Column Mapping";color:root.fg;font.bold:true}RowLayout{Layout.fillWidth:true;spacing:1;H{t:"Standard Field";Layout.preferredWidth:190}H{t:"Master Column";Layout.fillWidth:true}H{t:"Uploaded Column";Layout.fillWidth:true}H{t:"Confidence";Layout.preferredWidth:90}}ListView{Layout.fillWidth:true;Layout.fillHeight:true;model:mapRows;clip:true;delegate:Rectangle{required property int index;required property string f;required property string m;required property string u;required property real c;width:ListView.view.width;height:28;color:index%2?"#0d1b2e":"#0b1829";RowLayout{anchors.fill:parent;Text{text:f;color:root.fg;leftPadding:6;Layout.preferredWidth:190}Text{text:m||"Not detected";color:m?root.fg:root.red;leftPadding:6;Layout.fillWidth:true}Text{text:u||"Not detected";color:u?root.fg:root.red;leftPadding:6;Layout.fillWidth:true}Text{text:Math.round(c)+"%";color:c>=90?root.green:c>=70?root.amber:root.red;Layout.preferredWidth:90}}}}}}
    GridLayout{Layout.fillWidth:true;Layout.leftMargin:22;Layout.rightMargin:22;columns:4;columnSpacing:8;Metric{n:String(root.total);l:"TOTAL";Layout.fillWidth:true}Metric{n:String(root.correct);l:"CORRECT";nc:root.green;Layout.fillWidth:true}Metric{n:String(root.review);l:"REVIEW";nc:root.amber;Layout.fillWidth:true}Metric{n:String(root.errors);l:"ERROR";nc:root.red;Layout.fillWidth:true}}
    Panel{Layout.fillWidth:true;Layout.leftMargin:22;Layout.rightMargin:22;implicitHeight:275;ColumnLayout{anchors.fill:parent;anchors.margins:10;RowLayout{Layout.fillWidth:true;Text{text:"Validation Results — click a row";color:root.fg;font.bold:true}Item{Layout.fillWidth:true}Btn{text:"Export Report";enabled:valRows.count>0;onClicked:reportSave.open()}}RowLayout{Layout.fillWidth:true;spacing:1;H{t:"Row";Layout.preferredWidth:55}H{t:"SID";Layout.preferredWidth:110}H{t:"Store Name";Layout.preferredWidth:210}H{t:"Status";Layout.preferredWidth:90}H{t:"Summary";Layout.fillWidth:true}}ListView{Layout.fillWidth:true;Layout.fillHeight:true;model:valRows;clip:true;delegate:Rectangle{required property int index;required property string row;required property string sid;required property string store;required property string status;required property string problem;width:ListView.view.width;height:32;color:root.selectedRow===index?"#17375f":index%2?"#0d1b2e":"#0b1829";MouseArea{anchors.fill:parent;onClicked:{root.selectedRow=index;backend.getComparisonDetail(index,root.differencesOnly)}}RowLayout{anchors.fill:parent;Text{text:row;color:root.muted;leftPadding:6;Layout.preferredWidth:55}Text{text:sid;color:root.fg;leftPadding:6;Layout.preferredWidth:110}Text{text:store;color:root.fg;leftPadding:6;Layout.preferredWidth:210;elide:Text.ElideRight}Text{text:status;color:root.scol(status);font.bold:true;leftPadding:6;Layout.preferredWidth:90}Text{text:problem;color:root.fg;leftPadding:6;Layout.fillWidth:true;elide:Text.ElideRight}}}}}}
    Panel{Layout.fillWidth:true;Layout.leftMargin:22;Layout.rightMargin:22;implicitHeight:350;ColumnLayout{anchors.fill:parent;anchors.margins:10;RowLayout{Layout.fillWidth:true;Text{text:"Field-by-Field Comparison";color:root.fg;font.bold:true}Item{Layout.fillWidth:true}CheckBox{text:"Differences only";checked:root.differencesOnly;onToggled:{root.differencesOnly=checked;if(root.selectedRow>=0)backend.getComparisonDetail(root.selectedRow,checked)}}}RowLayout{Layout.fillWidth:true;spacing:1;H{t:"Field";Layout.preferredWidth:190}H{t:"Master Value";Layout.fillWidth:true}H{t:"Uploaded Value";Layout.fillWidth:true}H{t:"Result";Layout.preferredWidth:130}}ListView{Layout.fillWidth:true;Layout.fillHeight:true;model:compareRows;clip:true;delegate:Rectangle{required property string f;required property string m;required property string u;required property string res;required property string sev;width:ListView.view.width;height:35;color:root.bg(sev);RowLayout{anchors.fill:parent;Text{text:f;color:root.fg;font.bold:true;leftPadding:6;Layout.preferredWidth:190}Text{text:m;color:root.fg;leftPadding:6;Layout.fillWidth:true;elide:Text.ElideRight}Text{text:u;color:root.fg;leftPadding:6;Layout.fillWidth:true;elide:Text.ElideRight}Text{text:res;color:root.scol(sev);font.bold:true;leftPadding:6;Layout.preferredWidth:130}}}}}}
    Item{implicitHeight:18}
   }}}

   Item{ScrollView{anchors.fill:parent;contentWidth:availableWidth;ColumnLayout{width:parent.width;spacing:12;Item{implicitHeight:8}Title{text:"Repair CSV / Text";Layout.leftMargin:22}Desc{text:"Yellow = reconstructed multi-line record. Red = structural problem requiring fallback. The source remains untouched.";Layout.fillWidth:true;Layout.leftMargin:22;Layout.rightMargin:22}
    Panel{Layout.fillWidth:true;Layout.leftMargin:22;Layout.rightMargin:22;implicitHeight:90;RowLayout{anchors.fill:parent;anchors.margins:12;TextField{Layout.fillWidth:true;readOnly:true;placeholderText:"CSV / TXT / TSV";text:root.name(root.repairPath)}Btn{text:"Choose File";onClicked:repairDlg.open()}PBtn{text:"Repair & Save Copy";enabled:root.repairPath!=="";onClicked:repairSave.open()}}}
    Panel{Layout.fillWidth:true;Layout.leftMargin:22;Layout.rightMargin:22;implicitHeight:610;ColumnLayout{anchors.fill:parent;anchors.margins:10;Text{text:"Repair Audit — "+fixRows.count+" issue(s)";color:root.fg;font.bold:true}RowLayout{Layout.fillWidth:true;spacing:1;H{t:"Physical Line(s)";Layout.preferredWidth:105}H{t:"Expected";Layout.preferredWidth:75}H{t:"Actual";Layout.preferredWidth:70}H{t:"Status";Layout.preferredWidth:100}H{t:"What Happened";Layout.preferredWidth:310}H{t:"Original Information";Layout.fillWidth:true}}ListView{Layout.fillWidth:true;Layout.fillHeight:true;model:fixRows;clip:true;delegate:Rectangle{required property string line;required property string exp;required property string act;required property string status;required property string repair;required property string content;width:ListView.view.width;height:42;color:root.bg(status);RowLayout{anchors.fill:parent;Text{text:line;color:root.fg;leftPadding:6;Layout.preferredWidth:105}Text{text:exp;color:root.fg;leftPadding:6;Layout.preferredWidth:75}Text{text:act;color:root.fg;leftPadding:6;Layout.preferredWidth:70}Text{text:status;color:root.scol(status);font.bold:true;leftPadding:6;Layout.preferredWidth:100}Text{text:repair;color:root.fg;leftPadding:6;Layout.preferredWidth:310;elide:Text.ElideRight}Text{text:content;color:root.fg;leftPadding:6;Layout.fillWidth:true;elide:Text.ElideRight}}}}}}
   }}}

   Item{ScrollView{anchors.fill:parent;contentWidth:availableWidth;ColumnLayout{width:parent.width;spacing:12;Item{implicitHeight:8}Title{text:"Data Health & Statistics";Layout.leftMargin:22}Desc{text:"Profile the file, then calculate Count, Distinct Count, Blank Count, Sum, Average, Minimum, Maximum or Median with optional grouping.";Layout.fillWidth:true;Layout.leftMargin:22;Layout.rightMargin:22}
    Panel{Layout.fillWidth:true;Layout.leftMargin:22;Layout.rightMargin:22;implicitHeight:85;RowLayout{anchors.fill:parent;anchors.margins:12;Text{text:root.analysisPath?root.name(root.analysisPath):"No dataset selected";color:root.fg;font.bold:true;Layout.fillWidth:true}PBtn{text:"Choose Dataset";onClicked:dataDlg.open()}}}
    GridLayout{Layout.fillWidth:true;Layout.leftMargin:22;Layout.rightMargin:22;columns:4;columnSpacing:8;Metric{n:root.health.rows!==undefined?String(root.health.rows):"0";l:"ROWS";Layout.fillWidth:true}Metric{n:root.health.columns!==undefined?String(root.health.columns):"0";l:"COLUMNS";Layout.fillWidth:true}Metric{n:root.health.completeness!==undefined?String(root.health.completeness)+"%":"0%";l:"COMPLETENESS";nc:root.green;Layout.fillWidth:true}Metric{n:root.health.duplicateRows!==undefined?String(root.health.duplicateRows):"0";l:"DUPLICATE ROWS";nc:root.amber;Layout.fillWidth:true}}
    Panel{Layout.fillWidth:true;Layout.leftMargin:22;Layout.rightMargin:22;implicitHeight:300;ColumnLayout{anchors.fill:parent;anchors.margins:10;Text{text:"Column Quality";color:root.fg;font.bold:true}RowLayout{Layout.fillWidth:true;spacing:1;H{t:"Column";Layout.fillWidth:true}H{t:"Non-Blank";Layout.preferredWidth:90}H{t:"Blank";Layout.preferredWidth:75}H{t:"Unique";Layout.preferredWidth:75}H{t:"Duplicates";Layout.preferredWidth:85}H{t:"Numeric";Layout.preferredWidth:75}}ListView{Layout.fillWidth:true;Layout.fillHeight:true;model:healthRows;clip:true;delegate:Rectangle{required property int index;required property string col;required property string non;required property string blank;required property string uniq;required property string dup;required property string num;width:ListView.view.width;height:30;color:index%2?"#0d1b2e":"#0b1829";RowLayout{anchors.fill:parent;Text{text:col;color:root.fg;leftPadding:6;Layout.fillWidth:true}Text{text:non;color:root.green;Layout.preferredWidth:90}Text{text:blank;color:Number(blank)>0?root.amber:root.muted;Layout.preferredWidth:75}Text{text:uniq;color:root.muted;Layout.preferredWidth:75}Text{text:dup;color:root.muted;Layout.preferredWidth:85}Text{text:num;color:root.muted;Layout.preferredWidth:75}}}}}}
    Panel{Layout.fillWidth:true;Layout.leftMargin:22;Layout.rightMargin:22;implicitHeight:300;ColumnLayout{anchors.fill:parent;anchors.margins:10;Text{text:"Statistics Builder";color:root.fg;font.bold:true}RowLayout{Layout.fillWidth:true;ComboBox{id:statCol;Layout.fillWidth:true}ComboBox{id:statOp;model:["Count","Distinct Count","Blank Count","Sum","Average","Minimum","Maximum","Median"];Layout.preferredWidth:170}ComboBox{id:statGroup;Layout.fillWidth:true}PBtn{text:"Calculate";enabled:root.columns.length>0;onClicked:backend.calculateStatistics(statCol.currentText,statOp.currentText,statGroup.currentIndex<=0?"":statGroup.currentText)}}RowLayout{Layout.fillWidth:true;spacing:1;H{t:"Group";Layout.fillWidth:true}H{t:"Result";Layout.fillWidth:true}}ListView{Layout.fillWidth:true;Layout.fillHeight:true;model:statRows;clip:true;delegate:Rectangle{required property int index;required property string g;required property string v;width:ListView.view.width;height:31;color:index%2?"#0d1b2e":"#0b1829";RowLayout{anchors.fill:parent;Text{text:g;color:root.fg;leftPadding:6;Layout.fillWidth:true}Text{text:v;color:root.green;leftPadding:6;Layout.fillWidth:true}}}}}}
    Item{implicitHeight:18}
   }}}

   Item{ColumnLayout{anchors.fill:parent;anchors.margins:20;spacing:10
    Title{text:"Explore & Analyze"} Desc{text:"Search the loaded dataset or run read-only SQL. Results preserve the selected columns and appear as a real table.";Layout.fillWidth:true}
    Panel{Layout.fillWidth:true;implicitHeight:82;RowLayout{anchors.fill:parent;anchors.margins:11;Text{text:root.analysisPath?root.name(root.analysisPath):"No dataset loaded";color:root.fg;font.bold:true;Layout.fillWidth:true}Btn{text:"Load Dataset";onClicked:dataDlg.open()}Btn{text:"Export Result";enabled:root.analysisPath!=="";onClicked:dataSave.open()}}}
    Panel{Layout.fillWidth:true;implicitHeight:155;ColumnLayout{anchors.fill:parent;anchors.margins:10;RowLayout{Layout.fillWidth:true;TextField{id:search;placeholderText:"Search records...";Layout.fillWidth:true}ComboBox{id:searchCol;Layout.preferredWidth:220}PBtn{text:"Search";enabled:root.analysisPath!=="";onClicked:backend.searchData(search.text,searchCol.currentIndex<=0?"":searchCol.currentText)}}RowLayout{Layout.fillWidth:true;TextArea{id:sql;text:"SELECT * FROM data LIMIT 100";color:root.fg;wrapMode:TextEdit.NoWrap;Layout.fillWidth:true;Layout.preferredHeight:65;background:Rectangle{radius:6;color:"#071321";border.width:1;border.color:root.border}}PBtn{text:"Run SQL";enabled:root.analysisPath!=="";onClicked:backend.runSQL(sql.text)}}}}
    Panel{Layout.fillWidth:true;Layout.fillHeight:true;ColumnLayout{anchors.fill:parent;anchors.margins:9;RowLayout{Layout.fillWidth:true;Text{text:"Result Table";color:root.fg;font.bold:true}Item{Layout.fillWidth:true}Text{id:resultInfo;text:"0 rows";color:root.muted}}
     Flickable{id:flick;Layout.fillWidth:true;Layout.fillHeight:true;clip:true;contentWidth:Math.max(width,root.resultColumns.length*180);contentHeight:tableCol.height;boundsBehavior:Flickable.StopAtBounds
      Column{id:tableCol;width:flick.contentWidth;spacing:1
       Row{height:34;Repeater{model:root.resultColumns;delegate:H{required property var modelData;width:180;height:34;t:String(modelData)}}}
       Repeater{model:resultRows;delegate:Rectangle{required property int index;required property var vals;width:tableCol.width;height:32;color:index%2?"#0d1b2e":"#0b1829";Row{anchors.fill:parent;Repeater{model:vals;delegate:Rectangle{required property var modelData;width:180;height:32;color:"transparent";border.width:1;border.color:"#17283d";Text{anchors.fill:parent;anchors.margins:5;text:String(modelData===null?"":modelData);color:root.fg;font.pixelSize:10;verticalAlignment:Text.AlignVCenter;elide:Text.ElideRight}}}}}}
      }
      ScrollBar.vertical:ScrollBar{};ScrollBar.horizontal:ScrollBar{}
     }
    }}
   }}
  }
 }
}
