import QtQuick
import QtQuick.Controls
import QtQuick.Layouts
import QtQuick.Dialogs

ApplicationWindow {
 id:root; visible:true; width:1440; height:900; minimumWidth:1050; minimumHeight:680
 title:"Store Data Assistant 6.1"; color:"#07111f"
 property color fg:"#f8fafc"; property color muted:"#94a3b8"; property color panel:"#0e1b2d"; property color panel2:"#132238"; property color border:"#263850"; property color blue:"#3b82f6"; property color green:"#22c55e"; property color amber:"#f59e0b"; property color red:"#ef4444"
 property int page:0; property string masterPath:""; property string mappingPath:""; property string repairPath:""; property string analysisPath:""; property int total:0; property int correct:0; property int review:0; property int errors:0; property var health:({})
 ListModel{id:mapRows} ListModel{id:valRows} ListModel{id:fixRows} ListModel{id:healthRows} ListModel{id:sqlRows}
 function fname(p){var a=String(p||"").replace(/\\/g,"/").split("/");return a[a.length-1]||""}

 FileDialog{id:masterDlg;nameFilters:["Data (*.csv *.xlsx *.xls *.xlsm *.txt *.tsv *.json *.xml)"];onAccepted:{root.masterPath=selectedFile.toString();backend.loadMaster(root.masterPath)}}
 FileDialog{id:mappingDlg;nameFilters:["Data (*.csv *.xlsx *.xls *.xlsm *.txt *.tsv *.json *.xml)"];onAccepted:{root.mappingPath=selectedFile.toString();backend.loadMapping(root.mappingPath)}}
 FileDialog{id:repairDlg;nameFilters:["CSV/Text (*.csv *.txt *.tsv)"];onAccepted:{root.repairPath=selectedFile.toString();backend.inspectCSV(root.repairPath)}}
 FileDialog{id:analysisDlg;nameFilters:["Data (*.csv *.xlsx *.xls *.xlsm *.txt *.tsv *.json *.xml)"];onAccepted:{root.analysisPath=selectedFile.toString();backend.loadFile(root.analysisPath)}}
 FileDialog{id:repairSave;fileMode:FileDialog.SaveFile;nameFilters:["CSV (*.csv)"];onAccepted:backend.repairCSV(root.repairPath,selectedFile.toString())}
 FileDialog{id:reportSave;fileMode:FileDialog.SaveFile;nameFilters:["Excel (*.xlsx)","CSV (*.csv)"];onAccepted:backend.exportValidationReport(selectedFile.toString())}
 FileDialog{id:dataSave;fileMode:FileDialog.SaveFile;nameFilters:["Excel (*.xlsx)","CSV (*.csv)","JSON (*.json)"];onAccepted:backend.exportCurrentData(selectedFile.toString())}

 Connections{
  target:backend
  function onColumnMappingReady(s){var d=JSON.parse(s),f=["Store Name","SID","Banner","Nielsen Store Code","Trip Received","Last Trip","Address 1","Address 2","Address 3","ZIP","Active / Inactive","Is Census","Is Exceptions","Updated By"];mapRows.clear();for(var i=0;i<f.length;i++){var m=d.master[f[i]]||{},x=d.mapping[f[i]]||{};mapRows.append({field:f[i],master:String(m.column||""),mapping:String(x.column||""),confidence:Math.min(Number(m.confidence||0),Number(x.confidence||0))})}}
  function onValidationReady(s){var d=JSON.parse(s);root.total=d.total;root.correct=d.correct;root.review=d.review;root.errors=d.errors;valRows.clear();for(var i=0;i<d.results.length;i++){var x=d.results[i];valRows.append({row:String(x.row),sid:String(x.sid||""),store:String(x.storeName||""),status:String(x.status||""),problem:String(x.problem||"")})}}
  function onCsvInspectionReady(s){var d=JSON.parse(s);fixRows.clear();for(var i=0;i<d.problems.length;i++){var x=d.problems[i];fixRows.append({line:String(x.line),expected:String(x.expectedColumns),actual:String(x.actualColumns),content:String(x.content||"")})}}
  function onAnalysisReady(s){var d=JSON.parse(s);root.health=d;healthRows.clear();for(var i=0;i<d.columnStats.length;i++){var x=d.columnStats[i];healthRows.append({column:String(x.column),blank:String(x.blank),nonBlank:String(x.nonBlank),unique:String(x.unique),dupes:String(x.duplicateValues)})}}
  function onSqlResultReady(s){var d=JSON.parse(s);sqlRows.clear();for(var i=0;i<d.rows.length;i++)sqlRows.append({value:JSON.stringify(d.rows[i])})}
 }
 component Card:Rectangle{radius:9;color:root.panel;border.color:root.border}
 component Heading:Text{color:root.fg;font.pixelSize:22;font.bold:true}
 component Sub:Text{color:root.muted;font.pixelSize:12}
 component Btn:Button{implicitHeight:38;palette.button:root.panel2;palette.buttonText:root.fg}
 component PBtn:Button{implicitHeight:38;palette.button:root.blue;palette.buttonText:"white";font.bold:true}
 component HCell:Rectangle{property string label:"";color:root.panel2;implicitHeight:33;Text{anchors.fill:parent;anchors.margins:7;text:parent.label;color:root.muted;font.pixelSize:10;font.bold:true;verticalAlignment:Text.AlignVCenter;elide:Text.ElideRight}}
 component Metric:Card{property string number:"0";property string label:"";property color ncolor:root.blue;implicitHeight:78;Column{anchors.fill:parent;anchors.margins:12;spacing:4;Text{text:parent.parent.number;color:parent.parent.ncolor;font.pixelSize:22;font.bold:true}Text{text:parent.parent.label;color:root.muted;font.pixelSize:9;font.bold:true}}}

 header:Rectangle{height:56;color:"#081321";border.color:root.border;RowLayout{anchors.fill:parent;anchors.margins:11;Rectangle{width:32;height:32;radius:7;color:root.blue;Text{anchors.centerIn:parent;text:"DA";color:"white";font.bold:true}}Column{Text{text:"Store Data Assistant";color:root.fg;font.bold:true;font.pixelSize:15}Text{text:"Local validation, repair and analysis";color:root.muted;font.pixelSize:9}}Item{Layout.fillWidth:true}Text{text:"●  LOCAL ONLY";color:"#86efac";font.pixelSize:10;font.bold:true}}}
 footer:Rectangle{height:29;color:"#081321";border.color:root.border;RowLayout{anchors.fill:parent;anchors.leftMargin:12;anchors.rightMargin:12;Text{text:backend.message;color:root.muted;font.pixelSize:10;Layout.fillWidth:true;elide:Text.ElideRight}ProgressBar{visible:backend.busy;from:0;to:100;value:backend.progress;Layout.preferredWidth:140}}}

 RowLayout{anchors.fill:parent;spacing:0
  Rectangle{Layout.preferredWidth:205;Layout.fillHeight:true;color:"#0b1728";border.color:root.border;ColumnLayout{anchors.fill:parent;anchors.margins:10;Text{text:"WORKSPACE";color:root.muted;font.pixelSize:9;font.bold:true;Layout.margins:8}Repeater{model:["Home","Compare & Validate","Repair CSV / Text","Data Health Check","Explore & Analyze"];Button{required property string modelData;required property int index;Layout.fillWidth:true;implicitHeight:41;text:modelData;palette.button:root.page===index?"#1d4777":"#0b1728";palette.buttonText:root.fg;onClicked:root.page=index}}Item{Layout.fillHeight:true}Card{Layout.fillWidth:true;implicitHeight:65;Text{anchors.fill:parent;anchors.margins:9;text:"Privacy\nFiles are processed locally.";color:root.muted;font.pixelSize:9;wrapMode:Text.WordWrap}}}}
  StackLayout{currentIndex:root.page;Layout.fillWidth:true;Layout.fillHeight:true

   Item{ScrollView{anchors.fill:parent;contentWidth:availableWidth;ColumnLayout{width:parent.width;anchors.margins:25;spacing:15;Heading{text:"Welcome"}Sub{text:"Choose the workspace for the job you need to perform."}GridLayout{Layout.fillWidth:true;columns:root.width>1250?2:1;columnSpacing:12;rowSpacing:12;Repeater{model:[["Compare & Validate","Compare a store/country file with a trusted master.",1],["Repair CSV / Text","Inspect malformed records and save a repaired copy.",2],["Data Health Check","Profile completeness, blanks and duplicates.",3],["Explore & Analyze","Run local read-only SQL and export general datasets.",4]];Card{required property var modelData;Layout.fillWidth:true;implicitHeight:125;ColumnLayout{anchors.fill:parent;anchors.margins:15;Text{text:modelData[0];color:root.fg;font.pixelSize:15;font.bold:true}Sub{text:modelData[1];wrapMode:Text.WordWrap;Layout.fillWidth:true}Item{Layout.fillHeight:true}PBtn{text:"Open Workspace";onClicked:root.page=modelData[2]}}}}}}}}

   Item{ScrollView{anchors.fill:parent;contentWidth:availableWidth;ColumnLayout{width:parent.width;anchors.margins:23;spacing:13
    Heading{text:"Compare & Validate"} Sub{text:"Country-specific headers are mapped to the approved 14 standard fields."}
    Card{Layout.fillWidth:true;implicitHeight:155;ColumnLayout{anchors.fill:parent;anchors.margins:14;spacing:9;RowLayout{Layout.fillWidth:true;TextField{Layout.fillWidth:true;readOnly:true;placeholderText:"Master file";text:root.fname(root.masterPath)}Btn{text:"Browse";onClicked:masterDlg.open()}}RowLayout{Layout.fillWidth:true;TextField{Layout.fillWidth:true;readOnly:true;placeholderText:"Mapping / country file";text:root.fname(root.mappingPath)}Btn{text:"Browse";onClicked:mappingDlg.open()}}RowLayout{Layout.fillWidth:true;Btn{text:"Detect Columns";enabled:root.masterPath!==""&&root.mappingPath!=="";onClicked:backend.detectStoreColumns()}PBtn{text:"Validate Stores";Layout.fillWidth:true;enabled:root.masterPath!==""&&root.mappingPath!=="";onClicked:backend.validateStores()}}}}
    Card{Layout.fillWidth:true;implicitHeight:310;ColumnLayout{anchors.fill:parent;anchors.margins:12;spacing:1;Text{text:"Smart Column Mapping";color:root.fg;font.bold:true;font.pixelSize:14;Layout.bottomMargin:7}RowLayout{Layout.fillWidth:true;spacing:1;HCell{label:"Standard Field";Layout.preferredWidth:180}HCell{label:"Master";Layout.fillWidth:true}HCell{label:"Mapping";Layout.fillWidth:true}HCell{label:"Confidence";Layout.preferredWidth:90}}ListView{Layout.fillWidth:true;Layout.fillHeight:true;model:mapRows;clip:true;delegate:Rectangle{width:ListView.view.width;height:27;color:index%2?"#0d1b2e":"#0b1829";RowLayout{anchors.fill:parent;Text{text:field;color:root.fg;leftPadding:7;Layout.preferredWidth:180;elide:Text.ElideRight}Text{text:master||"Not detected";color:master?root.fg:root.red;leftPadding:7;Layout.fillWidth:true;elide:Text.ElideRight}Text{text:mapping||"Not detected";color:mapping?root.fg:root.red;leftPadding:7;Layout.fillWidth:true;elide:Text.ElideRight}Text{text:Math.round(confidence)+"%";color:confidence>=90?root.green:(confidence>=70?root.amber:root.red);Layout.preferredWidth:90;horizontalAlignment:Text.AlignHCenter}}}}}}
    GridLayout{Layout.fillWidth:true;columns:4;columnSpacing:9;Metric{number:String(root.total);label:"TOTAL";Layout.fillWidth:true}Metric{number:String(root.correct);label:"CORRECT";ncolor:root.green;Layout.fillWidth:true}Metric{number:String(root.review);label:"REVIEW";ncolor:root.amber;Layout.fillWidth:true}Metric{number:String(root.errors);label:"ERROR";ncolor:root.red;Layout.fillWidth:true}}
    Card{Layout.fillWidth:true;implicitHeight:380;ColumnLayout{anchors.fill:parent;anchors.margins:12;spacing:7;RowLayout{Layout.fillWidth:true;Text{text:"Validation Results";color:root.fg;font.bold:true;font.pixelSize:14}Item{Layout.fillWidth:true}Btn{text:"Export Report";enabled:valRows.count>0;onClicked:reportSave.open()}}RowLayout{Layout.fillWidth:true;spacing:1;HCell{label:"Row";Layout.preferredWidth:50}HCell{label:"SID";Layout.preferredWidth:105}HCell{label:"Store Name";Layout.preferredWidth:180}HCell{label:"Status";Layout.preferredWidth:80}HCell{label:"Problem";Layout.fillWidth:true}}ListView{Layout.fillWidth:true;Layout.fillHeight:true;model:valRows;clip:true;delegate:Rectangle{width:ListView.view.width;height:30;color:index%2?"#0d1b2e":"#0b1829";RowLayout{anchors.fill:parent;Text{text:row;color:root.muted;leftPadding:7;Layout.preferredWidth:50}Text{text:sid;color:root.fg;leftPadding:7;Layout.preferredWidth:105;elide:Text.ElideRight}Text{text:store;color:root.fg;leftPadding:7;Layout.preferredWidth:180;elide:Text.ElideRight}Text{text:status;color:status==="ERROR"?root.red:(status==="REVIEW"?root.amber:root.green);font.bold:true;leftPadding:7;Layout.preferredWidth:80}Text{text:problem;color:root.fg;leftPadding:7;Layout.fillWidth:true;elide:Text.ElideRight}}}}}}
   }}}}

   Item{ScrollView{anchors.fill:parent;contentWidth:availableWidth;ColumnLayout{width:parent.width;anchors.margins:23;spacing:13;Heading{text:"Repair CSV / Text"}Sub{text:"Quoted commas are handled by the CSV parser. Structural problems are shown before repair."}Card{Layout.fillWidth:true;implicitHeight:95;RowLayout{anchors.fill:parent;anchors.margins:14;TextField{Layout.fillWidth:true;readOnly:true;placeholderText:"CSV / TXT / TSV";text:root.fname(root.repairPath)}Btn{text:"Choose File";onClicked:repairDlg.open()}PBtn{text:"Repair & Save Copy";enabled:root.repairPath!=="";onClicked:repairSave.open()}}}Card{Layout.fillWidth:true;implicitHeight:500;ColumnLayout{anchors.fill:parent;anchors.margins:12;spacing:7;Text{text:"Broken Record Inspector — "+fixRows.count+" issue(s)";color:root.fg;font.bold:true;font.pixelSize:14}RowLayout{Layout.fillWidth:true;spacing:1;HCell{label:"Record";Layout.preferredWidth:65}HCell{label:"Expected";Layout.preferredWidth:80}HCell{label:"Actual";Layout.preferredWidth:80}HCell{label:"Original information";Layout.fillWidth:true}}ListView{Layout.fillWidth:true;Layout.fillHeight:true;model:fixRows;clip:true;delegate:Rectangle{width:ListView.view.width;height:31;color:index%2?"#0d1b2e":"#0b1829";RowLayout{anchors.fill:parent;Text{text:line;color:root.amber;leftPadding:7;Layout.preferredWidth:65}Text{text:expected;color:root.muted;leftPadding:7;Layout.preferredWidth:80}Text{text:actual;color:root.red;leftPadding:7;Layout.preferredWidth:80}Text{text:content;color:root.fg;leftPadding:7;Layout.fillWidth:true;elide:Text.ElideRight}}}}}}}}}

   Item{ScrollView{anchors.fill:parent;contentWidth:availableWidth;ColumnLayout{width:parent.width;anchors.margins:23;spacing:13;Heading{text:"Data Health Check"}Sub{text:"General-purpose local profiling for supported structured datasets."}Card{Layout.fillWidth:true;implicitHeight:90;RowLayout{anchors.fill:parent;anchors.margins:14;Text{text:root.analysisPath?root.fname(root.analysisPath):"No dataset selected";color:root.fg;font.bold:true;Layout.fillWidth:true}PBtn{text:"Choose Dataset";onClicked:analysisDlg.open()}}}GridLayout{Layout.fillWidth:true;columns:4;columnSpacing:9;Metric{number:health.rows!==undefined?String(health.rows):"0";label:"ROWS";Layout.fillWidth:true}Metric{number:health.columns!==undefined?String(health.columns):"0";label:"COLUMNS";Layout.fillWidth:true}Metric{number:health.completeness!==undefined?String(health.completeness)+"%":"0%";label:"COMPLETENESS";ncolor:root.green;Layout.fillWidth:true}Metric{number:health.duplicateRows!==undefined?String(health.duplicateRows):"0";label:"DUPLICATE ROWS";ncolor:root.amber;Layout.fillWidth:true}}Card{Layout.fillWidth:true;implicitHeight:470;ColumnLayout{anchors.fill:parent;anchors.margins:12;spacing:7;Text{text:"Column Quality";color:root.fg;font.bold:true;font.pixelSize:14}RowLayout{Layout.fillWidth:true;spacing:1;HCell{label:"Column";Layout.fillWidth:true}HCell{label:"Non-Blank";Layout.preferredWidth:95}HCell{label:"Blank";Layout.preferredWidth:80}HCell{label:"Unique";Layout.preferredWidth:80}HCell{label:"Duplicate Values";Layout.preferredWidth:115}}ListView{Layout.fillWidth:true;Layout.fillHeight:true;model:healthRows;clip:true;delegate:Rectangle{width:ListView.view.width;height:30;color:index%2?"#0d1b2e":"#0b1829";RowLayout{anchors.fill:parent;Text{text:column;color:root.fg;leftPadding:7;Layout.fillWidth:true;elide:Text.ElideRight}Text{text:nonBlank;color:root.green;leftPadding:7;Layout.preferredWidth:95}Text{text:blank;color:Number(blank)>0?root.amber:root.muted;leftPadding:7;Layout.preferredWidth:80}Text{text:unique;color:root.muted;leftPadding:7;Layout.preferredWidth:80}Text{text:dupes;color:root.muted;leftPadding:7;Layout.preferredWidth:115}}}}}}}}}

   Item{ScrollView{anchors.fill:parent;contentWidth:availableWidth;ColumnLayout{width:parent.width;anchors.margins:23;spacing:13;Heading{text:"Explore & Analyze"}Sub{text:"SQL is intentionally available only in this final analysis workspace and is read-only."}Card{Layout.fillWidth:true;implicitHeight:90;RowLayout{anchors.fill:parent;anchors.margins:14;Text{text:root.analysisPath?root.fname(root.analysisPath):"No dataset loaded";color:root.fg;font.bold:true;Layout.fillWidth:true}Btn{text:"Load Dataset";onClicked:analysisDlg.open()}Btn{text:"Export Data";enabled:root.analysisPath!=="";onClicked:dataSave.open()}}}Card{Layout.fillWidth:true;implicitHeight:205;ColumnLayout{anchors.fill:parent;anchors.margins:12;spacing:7;Text{text:"SQL Workspace";color:root.fg;font.bold:true;font.pixelSize:14}Sub{text:"Table name: data   •   Example: SELECT * FROM data LIMIT 100"}TextArea{id:sql;Layout.fillWidth:true;Layout.fillHeight:true;color:root.fg;placeholderText:"SELECT * FROM data LIMIT 100";background:Rectangle{radius:6;color:"#071321";border.color:root.border}}RowLayout{Layout.fillWidth:true;Item{Layout.fillWidth:true}PBtn{text:"Run SQL";enabled:root.analysisPath!==""&&sql.text.trim()!=="";onClicked:backend.runSQL(sql.text)}}}}Card{Layout.fillWidth:true;implicitHeight:430;ColumnLayout{anchors.fill:parent;anchors.margins:12;Text{text:"Query Results — "+sqlRows.count+" row(s)";color:root.fg;font.bold:true;font.pixelSize:14;Layout.bottomMargin:7}ListView{Layout.fillWidth:true;Layout.fillHeight:true;model:sqlRows;clip:true;delegate:Rectangle{width:ListView.view.width;height:32;color:index%2?"#0d1b2e":"#0b1829";Text{anchors.fill:parent;anchors.margins:7;text:value;color:root.fg;font.pixelSize:10;elide:Text.ElideRight;verticalAlignment:Text.AlignVCenter}}}}}}}}
  }
 }
}
